import { Poppins } from "next/font/google";
import "./dashboard.css";
import Header from "./_components/header/Header";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mailbox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${poppins.className} bg-[white]`)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
