import { Poppins } from "next/font/google";
import "./dashboard.css";
import Header from "./_components/header/Header";
import { cn } from "@/lib/utils";
import MiniSideBar from "./_components/sidebar/MiniSideBar";
import SideBar from "./_components/sidebar/SideBar";
import TopHeader from "./_components/header/TopHeader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mailbox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${poppins.className} bg-[white] w-full`)}>
        <Header />
        <div className="flex w-full">
          <div className="w-fit bg-[green] min-h-screen">
            <MiniSideBar />
          </div>
          <div className="flex flex-col w-full">
            <div className="w-full">
              <TopHeader />
            </div>
            <div className="flex">
              <div className="w-[18%] bg-[yellow] min-h-screen">
                <SideBar />
              </div>
              <div className="w-[22%] bg-[orange]"></div>
              <div className="w-[60%] bg-[green] p-10 h-screen">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
